name: emotion_cam_360
description: Show cam 360
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
#dependency_overrides:
#  ffi: ^2.0.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.11.0"


#Firebase
  firebase_core: ^2.1.1
  cloud_firestore:
  firebase_auth:
  google_sign_in: ^6.0.2
  firebase_storage: ^11.0.6


#UI
  page_indicator: ^0.4.1
  flutter_hooks: 
  image_picker: ^0.8.4+2
  cached_network_image: ^3.1.0
  carousel_slider: ^4.2.1
  camera: ^0.10.3
  simple_circular_progress_bar: ^1.0.2
  flutter_svg: ^1.1.6
  otp_text_field: ^1.1.3
  timer_button: ^2.0.0
  file_picker: ^5.2.5
  liquid_progress_indicator: ^0.4.0
  share_plus: ^6.3.0
# gmo_media_picker: ^0.0.1
# wechat_assets_picker: ^8.3.1+1
# gmo_media_picker: ^0.0.4


#Video
#  ffmpeg_kit_flutter: 5.1.0 --enable-gpl
#  ffmpeg_kit_flutter_video: ^5.1.0
#  ffmpeg_kit_flutter_https-gpl: ^5.1.0
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
  path: ^1.8.1
  fluttertoast: ^8.0.9
  video_player: ^2.2.6 #^2.4.7

#Model
  uuid: ^3.0.6
  equatable: ^2.0.5
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11

#Persistencia de Datos
  flutter_secure_storage: ^7.0.1
  sqflite: ^2.2.2
  provider: ^6.0.5

#Util bd and State Managment
  http: ^0.13.5
  get: ^4.6.5


#Debug
  chalkdart: ^2.0.8
  #change_app_package_name: ^0.1.2



#open_file: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/themes/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

#ICONOS DE LA APP
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo-emotion.png"
  web:
    generate: true
    image_path: "assets/icon/logo-emotion.png"
    background_color: "#ffff"

  windows:
    generate: true
    image_path: "assets/icon/logo-emotion.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo-emotion.png"       