name: emotion_cam_360
description: Show cam 360
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

#Firebase
  firebase_core: ^2.1.1
  cloud_firestore:
  firebase_auth:
  google_sign_in: ^5.3.0
  firebase_storage: ^11.0.6
  flutter_secure_storage: ^4.0.2

#UI
  page_indicator: ^0.4.1
  flutter_hooks: 
  image_picker: ^0.8.4+2
  cached_network_image: ^3.1.0
  carousel_slider: ^4.2.1
  camera: ^0.10.0+5
  simple_circular_progress_bar: ^1.0.2
  video_player: ^2.2.6 #^2.4.7
  flutter_svg: ^0.22.0
  otp_text_field: ^1.1.3
  timer_button: ^2.0.0

#Video
  ffmpeg_kit_flutter_video: 5.1.0-LTS
  path: ^1.8.1
  fluttertoast: ^8.0.9


#Model
  uuid: ^3.0.6
  equatable: ^2.0.5
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11

#Util bd and State Managment
  http: ^0.13.5
  get: ^4.6.5
  sqflite: ^2.2.2


#Debug
  chalkdart: ^2.0.8



#open_file: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/themes/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf